import Link from 'next/link';
import './globals.css';
import type { Metadata } from 'next';
import { Control } from './Control';

export const metadata: Metadata = {
  title: 'Web tutorials',
  description: 'Generated by byein',
};
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL + 'topics', { cache: 'no-cache' });
  const topics = await resp.json();
  return (
    <html>
      <body>
        <h1>
          <Link href='/'>WEB</Link>
        </h1>
        <ol>
          {topics.map((topic: { id: number; title: string; body: string }) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
